#include "builtin.h"

#include "builtins/pwd.c"
#include "builtins/cd.c"
#include "builtins/echo.c"
#include "builtins/kill.c"
#include "builtins/true.c"
#include "builtins/false.c"
#include "builtins/shift.c"
#include "builtins/exit.c"
